export enum ApplicationPendingActionType {
  RESPOND_TO_MESSAGE = 'RESPOND_TO_MESSAGE',
  UPLOAD_REQUESTED_DOCUMENT = 'UPLOAD_REQUESTED_DOCUMENT',
  REVIEW_DOCUMENT = 'REVIEW_DOCUMENT',
  RESPOND_TO_VIEWING = 'RESPOND_TO_VIEWING',
  RESPOND_TO_VIEWING_CHANGE_REQUEST = 'RESPOND_TO_VIEWING_CHANGE_REQUEST',
  CLOSE_UNANSWERED_VIEWING = 'CLOSE_UNANSWERED_VIEWING',
  RECORD_VIEWING_OUTCOME = 'RECORD_VIEWING_OUTCOME',
  CONFIRM_POST_VIEWING_INTEREST = 'CONFIRM_POST_VIEWING_INTEREST',
}

export type AttentionAudience = 'provider' | 'applicant';
